import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { makeRng } from '../src/monitor/prng.ts';

const SEED = '0x00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff';

test('the same seed gives the same sequence', () => {
  const a = Array.from({ length: 32 }, makeRng(SEED));
  const b = Array.from({ length: 32 }, makeRng(SEED));
  assert.deepEqual(a, b);
});

test('different seeds diverge', () => {
  const a = Array.from({ length: 32 }, makeRng(SEED));
  const b = Array.from({ length: 32 }, makeRng('0x' + 'ab'.repeat(32)));
  assert.notDeepEqual(a, b);
});

test('values stay in [0, 1)', () => {
  const rng = makeRng(SEED);
  for (let i = 0; i < 5000; i++) {
    const v = rng();
    assert.ok(v >= 0 && v < 1, `out of range: ${v}`);
  }
});

test('the 0x prefix is stripped before folding', () => {
  const a = Array.from({ length: 16 }, makeRng(SEED));
  const b = Array.from({ length: 16 }, makeRng(SEED.slice(2)));
  assert.deepEqual(a, b);
});

// The parity guard. If the game and the server ever disagree, every plausibility check silently
// becomes meaningless - so this must fail loudly instead.
test('the server PRNG is the same algorithm as the game PRNG', () => {
  const game = readFileSync(
    new URL('../../game/doodleshooter/src/prng.js', import.meta.url),
    'utf8',
  );
  assert.match(game, /0x6d2b79f5/, 'the game must still use mulberry32');
  assert.match(game, /0x811c9dc5/, 'the game must still fold the seed with the FNV-1a basis');
  assert.match(game, /0x01000193/, 'the game must still use the FNV-1a prime');
});

// Cross-implementation vector: these values were produced by the GAME's prng.js. If the server
// drifts, they stop matching.
test('the server reproduces a vector generated by the game', () => {
  const rng = makeRng('0x' + 'ab'.repeat(32));
  const got = Array.from({ length: 8 }, rng).map((v) => v.toFixed(12));
  const expected = JSON.parse(
    readFileSync(new URL('./fixtures/prng-vector.json', import.meta.url), 'utf8'),
  ) as string[];
  assert.deepEqual(got, expected);
});
