/// Mirror of the seeded PRNG in game/doodleshooter/src/prng.js.
/// If these ever diverge, every plausibility check silently becomes meaningless.
/// test/prng.test.ts guards it with a vector generated by the GAME's implementation.

export function foldSeed(seedHex: string): number {
  const hex = String(seedHex).replace(/^0x/i, '');
  let h = 0x811c9dc5 >>> 0; // FNV-1a offset basis
  for (let i = 0; i < hex.length; i++) {
    h ^= hex.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0; // FNV-1a prime
  }
  return h >>> 0;
}

export function makeRng(seedHex: string): () => number {
  let state = foldSeed(seedHex);
  return function mulberry32(): number {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
